server:
  servlet:
    encoding:
      charset: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/board?serverTimezone=UTC
    username: eden6187
    password: "!!dnwn556"

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      ddl-auto: create-drop
    open-in-view: false